## 1. Create a null vector of size 10 but the fifth value which is 1

In [16]:
import numpy as np

def create_null_vector(size):
    
    # Create a null vector of the specified size
    null_vector = np.zeros(size)

    # Set the fifth value to 1
    null_vector[4] = 1

    return null_vector

# Example usage:
size_of_vector = 10
null_vector = create_null_vector(size_of_vector)
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [15]:
import numpy as np

def create_vector(start, end):
    
    return np.arange(start, end)

# Example usage:
start_value = 10
end_value = 50
vector = create_vector(start_value, end_value)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np

def create_matrix():
    # Create a 1-dimensional array with values ranging from 0 to 8
    array_1d = np.arange(9)
    
    # Reshape the 1-dimensional array into a 3x3 matrix
    matrix_3x3 = array_1d.reshape(3, 3)
    
    return matrix_3x3

# Call the function
resulting_matrix = create_matrix()

print(resulting_matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
import numpy as np

def find_non_zero_indices(arr):
    # Find indices of non-zero elements
    non_zero_indices = np.nonzero(arr)
    
    return non_zero_indices

# Example usage:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = find_non_zero_indices(arr)
print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values

In [9]:
import numpy as np

def find_min_max():
    # Create a 10x10 array with random integer values between 0 and 100
    array = np.random.randint(0, 101, size=(10, 10))  # Generates integers between 0 and 100 inclusive
    
    # Find the minimum and maximum values
    min_value = np.min(array)
    max_value = np.max(array)
    
    return array, min_value, max_value

# Call the function
array, min_value, max_value = find_min_max()

print("Array:")
print(array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Array:
[[ 10  23  69  40   1  70  45  67  17  32]
 [ 38  97  17  39  10  90  12   7   5  68]
 [ 46 100   8  98  26  51  49  60  49  40]
 [ 24  18  30  15  10   8  21  98  66  98]
 [ 69  83  40  66  27  91  43  89  32   0]
 [ 59  21  51  20  98  22   9  87  68   2]
 [ 74  37  62  93  13  60  71  78  80  63]
 [ 82  24  91  85  84  58  10  65  38  41]
 [ 95  88  93  33  31  74   4  87  24  78]
 [ 93   5  69  78  56  55  10  96  51  99]]

Minimum value: 0
Maximum value: 100


## 6. Create a random vector of size 30 and find the mean value.


In [12]:
import numpy as np

def find_mean():
    # Create a random vector of size 30
    random_vector = np.random.randint(0,101,30)
    
    # Calculate the mean value
    mean_value = np.mean(random_vector)
    
    return random_vector, mean_value

# Call the function
random_vector, mean_value = find_mean()

print("Random Vector:")
print(random_vector)
print("\nMean value:", mean_value)


Random Vector:
[69  2 55  1  7 33 50 21 65 63  2 70  6 68 85 97 43 30 98 64 19 12  6 79
 83 62 53 40 45 11]

Mean value: 44.63333333333333
